# https://cloud.google.com/appengine/docs/standard/python3/config/appref
runtime: python38
entrypoint: gunicorn -b :$PORT main.application
x-google-allow: all
# handlers:
#   - url: /
#     http_headers:
#       Access-Control-Allow-Origin: https://d289aztbzuse4k.cloudfront.net
