# https://cloud.google.com/appengine/docs/standard/python3/config/appref
runtime: python37
entrypoint: gunicorn -b :$PORT application
handlers:
  - url: /
    http_headers:
      Access-Control-Allow-Origin: https://d289aztbzuse4k.cloudfront.net
